<div>
<img src=https://www.institutedata.com/wp-content/uploads/2019/10/iod_h_tp_primary_c.svg width="300">
</div>

# Lab 3.1.1 
# *Data Wrangling and Munging with Pandas*

## Part 1: Wrangling Data

The term "data wrangling" is analogous to capturing wild horses and getting them into a fenced area; the horses are data and the fencing is your computer. The more common data wrangling tasks include:

- reading flat files
- reading Excel files
- downloading from web pages
  - csv
  - html
  - json

In [18]:
import numpy as np
import pandas as pd

*It is good practice to display the library version numbers for future reference:*

In [19]:
print('Numpy: ', np.__version__)
print('Pandas: ', pd.__version__)

Numpy:  1.19.2
Pandas:  1.1.3


### CSV Files

Below are three attempts to load the file "bikeshare.csv" into a DataFrame named `bikes`. Why are they wrong?

In [22]:
# wrong:
bikes = pd.read_table('bikeshare.csv', header = None)
print(bikes.head())
print()

# wrong:
bikes = pd.read_table('bikeshare.csv', header = 1)
print(bikes.head())
print()

# wrong:
bikes = pd.read_table('bikeshare.csv', header = 0)
print(bikes.head())

                                                   0
0  instant,dteday,season,yr,mnth,hr,holiday,weekd...
1  1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,...
2  2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.8,0...
3  3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.8,0...
4  4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,...

  1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0,3,13,16
0  2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.8,0...     
1  3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.8,0...     
2  4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,...     
3  5,2011-01-01,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,...     
4  6,2011-01-01,1,0,1,5,0,6,0,2,0.24,0.2576,0.75,...     

  instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0  1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,...                                                                   
1  2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.8,0...                                        

?:
ANSWER: Case 1 treats headings as just another data row. Case 2 treats the 1st data row as the column header. Case 3 gets the header right (row 0), but reads each row as a single column (Nb. the other two make that same mistake). 

Load the file "bikeshare.csv" into a DataFrame named `bikes`, and confirm that it was loaded properly:

In [20]:
#ANSWER:
bikes = pd.read_csv("bikeshare.csv")
print(bikes.head())

   instant      dteday  season  yr  mnth  hr  holiday  weekday  workingday  \
0        1  2011-01-01       1   0     1   0        0        6           0   
1        2  2011-01-01       1   0     1   1        0        6           0   
2        3  2011-01-01       1   0     1   2        0        6           0   
3        4  2011-01-01       1   0     1   3        0        6           0   
4        5  2011-01-01       1   0     1   4        0        6           0   

   weathersit  temp   atemp   hum  windspeed  casual  registered  cnt  
0           1  0.24  0.2879  0.81        0.0       3          13   16  
1           1  0.22  0.2727  0.80        0.0       8          32   40  
2           1  0.22  0.2727  0.80        0.0       5          27   32  
3           1  0.24  0.2879  0.75        0.0       3          10   13  
4           1  0.24  0.2879  0.75        0.0       0           1    1  


Note that we could have used `read.csv()` above. When is `read_table()` necessary?

?:
ANSWER: When `sep` is not the comma character, or we need fine control that `read.csv()` does not provide.

Flat files can be full of surprises. Here are some issues to watch out for:

- separator character is something other than the comma
  - ";", "|", and tab are popular
- newline character is something other than what the O/S expects 
  - Tip: Don't hard-code the character codes for carriage returns, linefeeds, etc. Use Python's built-in representation instead (e.g. Python translates "\n" to the newline character and "\t" to the tab character on any O/S).
- truncated lines
  - if there are empty fields at the end of a line it is possible that their separators will be missing, resulting in a "jagged" file
- embedded commas or quotes
  - a free-text field containing embedded commas may split into separate fields on input
  - a free-text field containing embedded quotes may not parse correctly
- unescaped characters
  - the "\" character indicates a control code to Python, which will break the I/O
    - e.g. the substring "\u0123" will be interpreted as Unicode(0123) -- which may not be what the file creator intended
  - these may need to be fixed by loading whole strings and then parsing into a new data frame
  
Tip: Most issues can be delth with by correctly specifying the parameters of the function you use to load the file. Read the doco before reading the data!

### Reading Excel Files

In [21]:
from pandas import ExcelFile  # Nb. Need to install xlrd from conda (it does not automatically install with pandas)

In [36]:
df = pd.read_excel('Iris.xls', sheet_name = 'Data')
df

Species_No  Petal_width  Petal_length  Sepal_width  Sepal_length  \
0             1          0.2           1.4          3.5           5.1   
1             1          0.2           1.4          3.0           4.9   
2             1          0.2           1.3          3.2           4.7   
3             1          0.2           1.5          3.1           4.6   
4             1          0.2           1.4          3.6           5.0   
..          ...          ...           ...          ...           ...   
145           3          2.3           5.2          3.0           6.7   
146           3          1.9           5.0          2.5           6.3   
147           3          2.0           5.2          3.0           6.5   
148           3          2.3           5.4          3.4           6.2   
149           3          1.8           5.1          3.0           5.9   

    Species_name  
0         Setosa  
1         Setosa  
2         Setosa  
3         Setosa  
4         Setosa  
..           ...  
145    Verginica  
146    Verginica  
147    Verginica  
148    Verginica  
149    Verginica  

[150 rows x 6 columns]

So, this file appears to have an embedded table of aggregates on the same sheet as the raw data (a naughty but common practice amongst analysts).

It is usually better to load data correctly than to meddle with the source file or load it 'warts and all' and then try to parse it in code. The Pandas functions for reading files have parameters that provide the control we need. For ecxample, we could make multiple calls to `read_excel()`, using combinations of the `header`, `usecols`, `skiprows`, `nrows`, and `skipfooter` parameters to load one table at a time from a spreadsheet with multiple tables.

Load the above file without the unwanted columns:

In [37]:
#ANSWER
#remove species name column (because this is what the ML system is supposed to conclude)

df = pd.read_excel('Iris.xls', sheet_name = 'Data', usecols = [0,1,2,3,4])
df

Species_No  Petal_width  Petal_length  Sepal_width  Sepal_length
0             1          0.2           1.4          3.5           5.1
1             1          0.2           1.4          3.0           4.9
2             1          0.2           1.3          3.2           4.7
3             1          0.2           1.5          3.1           4.6
4             1          0.2           1.4          3.6           5.0
..          ...          ...           ...          ...           ...
145           3          2.3           5.2          3.0           6.7
146           3          1.9           5.0          2.5           6.3
147           3          2.0           5.2          3.0           6.5
148           3          2.3           5.4          3.4           6.2
149           3          1.8           5.1          3.0           5.9

[150 rows x 5 columns]

### Importing Data Directly from the Web

We usually want to store a local copy of a data file that we download from the Web, but when data retention is not a priority it is convenient to download the data directly into our running Python environment.

#### Importing Text Files from the Web

The web is the 'wild west' of data formats. However, we can usually expect good behaviour from files that are automatically generated by a service, such as the earthquake report:

In [38]:
df1 = pd.read_csv('https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/2.5_hour.csv')
df1.head()

time  latitude  longitude  depth  mag magType  nst  \
0  2021-06-04T13:45:15.342Z    0.3024   126.3626  21.12  5.2     mww  NaN   

   gap   dmin   rms  ...                   updated  \
0   53  1.107  1.28  ...  2021-06-04T14:01:57.040Z   

                              place        type horizontalError depthError  \
0  125 km WSW of Ternate, Indonesia  earthquake             6.2        5.8   

   magError  magNst    status  locationSource magSource  
0     0.093      11  reviewed              us        us  

[1 rows x 22 columns]

#### Importing HTML Files from the Web

Working with unstructured HTML files relies heavily on library functions. This one, however, is well-structured:

In [39]:
url = 'https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list/'

df2 = pd.read_html(url)
df2

[                         Bank NameBank           CityCity StateSt  CertCert  \
 0                    Almena State Bank             Almena      KS     15426   
 1           First City Bank of Florida  Fort Walton Beach      FL     16748   
 2                 The First State Bank      Barboursville      WV     14361   
 3                   Ericson State Bank            Ericson      NE     18265   
 4     City National Bank of New Jersey             Newark      NJ     21111   
 ..                                 ...                ...     ...       ...   
 558                 Superior Bank, FSB           Hinsdale      IL     32646   
 559                Malta National Bank              Malta      OH      6629   
 560    First Alliance Bank & Trust Co.         Manchester      NH     34264   
 561  National State Bank of Metropolis         Metropolis      IL      3815   
 562                   Bank of Honolulu           Honolulu      HI     21029   
 
                  Acquiring Institutio

#### Importing XML Files from the Web

XML files are semi-structured, but you're at the mercy of the file creator. If every record has the same format it will be much easier, but practical applications often require a lot of custom code. Here is an example that includes a nice parser class: http://www.austintaylor.io/lxml/python/pandas/xml/dataframe/2016/07/08/convert-xml-to-pandas-dataframe/

In [40]:
url1 = 'http://www.austintaylor.io/lxml/python/pandas/xml/dataframe/2016/07/08/convert-xml-to-pandas-dataframe/'

df3 = pd.read_html(url1)
df3

[   Unnamed: 0        ID                                             String  \
 0           0  id_a_f_3              !Susie (http://www.sync2it.com/susie)   
 1           1  id_a_f_6  <a href='http://www.unchaos.com/'> UnChaos </a...   
 2           2  id_a_f_7  <a href='http://www.unchaos.com/'> UnChaos Bot...   
 
                                        Description Type       Comment  \
 0  Sync2It bookmark management & clustering engine  C R          None   
 1                             UnCHAOS search robot    R  Site is dead   
 2                             UnCHAOS search robot    R  Site is dead   
 
                      Link1 Link2  
 0   http://www.sync2it.com  None  
 1  http://www.unchaos.com/  None  
 2  http://www.unchaos.com/  None  ]

#### Importing JSON Files from the Web

Like XML, JSON files are semi-structured and may require work to capture the schema into a dataframe. Here is a simple example: 

In [41]:
url2 = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/data.json'

# Load the first sheet of the JSON file into a data frame
df4 = pd.read_json(url2, orient = 'columns')
df4.head()

integer            datetime  category
0        5 2015-01-01 00:00:00         0
1        5 2015-01-01 00:00:01         0
2        9 2015-01-01 00:00:02         0
3        6 2015-01-01 00:00:03         0
4        6 2015-01-01 00:00:04         0

## Part 2: Data Munging

Data munging is manipulating data to get it into a form that we can start running analyses on (which usually means getting the data into a DataFrame). Before we get to this stage, we may need to remove headers or footers, transpose columns to rows, split wide data tables into long ones, and so on. (Nb. Excel files can be particularly troublesome, because users can format their data in mixed, complex shapes.) Essentially, we need to follow Hadley Wickham's guidelines for tidy datasets (http://vita.had.co.nz/papers/tidy-data.html):

The end goal of the cleaning data process:

- each variable should be in one column
- each observation should comprise one row
- each type of observational unit should form one table
- include key columns for linking multiple tables
- the top row contains (sensible) variable names
- in general, save data as one file per table


### Dataset Morphology

Once we have our dataset in a DataFrame (or Series, if our data is only 1-dimensional), we can start examining its size and content.

How many rows and columns are in `bikes`?

In [42]:
#ANSWER
#Get the number of rows: len(df)
#Get the number of columns: len(df.columns)
#Get the number of rows and columns (respectively): df.shape

df.shape

(150, 5)

What are the column names in `bikes`?

In [43]:
#ANSWER
for col in df.columns:
    print(col)

Species_No
Petal_width
Petal_length
Sepal_width
Sepal_length


What are the data types of these columns?

In [45]:
#ANSWER
datatypeseries = df.dtypes
print('data type of each column of dataframe :')
print(datatypeseries)

data type of each column of dataframe :
Species_No        int64
Petal_width     float64
Petal_length    float64
Sepal_width     float64
Sepal_length    float64
dtype: object


What is the (row) index for this DataFrame?

In [47]:
#ANSWER
df.index

RangeIndex(start=0, stop=150, step=1)

https://www.dataquest.io/blog/python-json-tutorial/

## Slicing and Dicing

It is often preferable to refer to DataFrame columns by name, but there is more than one way to do this. 
Do `bikes['season']` and `bikes[['season']]` give the same object? Demonstrate:

In [48]:
#ANSWER - part 1
print(bikes['season'])
print(type(bikes['season']))
# result will be panda series

0        1
1        1
2        1
3        1
4        1
        ..
17374    1
17375    1
17376    1
17377    1
17378    1
Name: season, Length: 17379, dtype: int64
<class 'pandas.core.series.Series'>


In [50]:
#ANSWER - part 2
print(bikes[['season']])
print(type(bikes[['season']]))
# result will be dataframe

#print(type(bikes[['season']].iloc[0]))

       season
0           1
1           1
2           1
3           1
4           1
...       ...
17374       1
17375       1
17376       1
17377       1
17378       1

[17379 rows x 1 columns]
<class 'pandas.core.frame.DataFrame'>


In [52]:
for col in bikes.columns:
    print(col)

instant
dteday
season
yr
mnth
hr
holiday
weekday
workingday
weathersit
temp
atemp
hum
windspeed
casual
registered
cnt


How would we use object notation to show the first 4 rows of `atemp`?

In [54]:
#ANSWER
#by indexing
bikes.iloc[0:4, 11]

0    0.2879
1    0.2727
2    0.2727
3    0.2879
Name: atemp, dtype: float64

In [72]:
print(bikes.head(3))

#using label
#note: .loc will ALWAYS interpret integers as labels, not as integer positions along index (must use .iloc for that)
bikes.loc[0:4, 'atemp']

   instant      dteday  season  yr  mnth  hr  holiday  weekday  workingday  \
0        1  2011-01-01       1   0     1   0        0        6           0   
1        2  2011-01-01       1   0     1   1        0        6           0   
2        3  2011-01-01       1   0     1   2        0        6           0   

   weathersit  temp   atemp   hum  windspeed  casual  registered  cnt  
0           1  0.24  0.2879  0.81        0.0       3          13   16  
1           1  0.22  0.2727  0.80        0.0       8          32   40  
2           1  0.22  0.2727  0.80        0.0       5          27   32  


0    0.2879
1    0.2727
2    0.2727
3    0.2879
4    0.2879
Name: atemp, dtype: float64

Algorithms that loop over multiple columns often access DataFrame columns by index. However, none of the following work (try them out by uncommenting / removing the "#E: " ): 

In [62]:
#bikes[[0]]
#E: bikes[0]
#E: bikes[0,0]
#E: bikes[[0,0]]

What is the correct way to access the 1st row of the DataFrame by its index?

In [73]:
#ANSWER
bikes.iloc[0, :]

instant                1
dteday        2011-01-01
season                 1
yr                     0
mnth                   1
hr                     0
holiday                0
weekday                6
workingday             0
weathersit             1
temp                0.24
atemp             0.2879
hum                 0.81
windspeed              0
casual                 3
registered            13
cnt                   16
Name: 0, dtype: object

What is the correct way to access the 2nd column of the DataFrame by its index?

In [74]:
#ANSWER
bikes.iloc[1, :]

instant                2
dteday        2011-01-01
season                 1
yr                     0
mnth                   1
hr                     1
holiday                0
weekday                6
workingday             0
weathersit             1
temp                0.22
atemp             0.2727
hum                  0.8
windspeed              0
casual                 8
registered            32
cnt                   40
Name: 1, dtype: object

## Handling Missing Values

What is the Pandas `isnull` function for? 

?
ANSWER:

In [ ]:
# Boolean: will tell you True/False depending on whether it is null value

We can apply `isnull` to the `bikes` DataFrame to show the result for every element:

In [76]:
bikes.isnull().head(3)

instant  dteday  season     yr   mnth     hr  holiday  weekday  workingday  \
0    False   False   False  False  False  False    False    False       False   
1    False   False   False  False  False  False    False    False       False   
2    False   False   False  False  False  False    False    False       False   

   weathersit   temp  atemp    hum  windspeed  casual  registered    cnt  
0       False  False  False  False      False   False       False  False  
1       False  False  False  False      False   False       False  False  
2       False  False  False  False      False   False       False  False

However, we usually start at a higher level. How many nulls are in `bikes` altogether?

In [79]:
#ANSWER
#bikes.isnull().sum() #sum of columns
bikes.isnull().sum().sum() #sum of columns' sums
#bikes.isnull().values.any() #tells you whether nulls exist in entire df

0

If this result were nonzero we would next want to find out which columns contained nulls. How can this be done in one line of code?

In [91]:
#ANSWER
#bikes.notnull().any()[lambda x: x] - not what qn is asking just own notes
#print(bikes.isnull().sum()) - sum of nulls in each column

bikes.isnull().any()[lambda x: x]
#produces names of columns where nulls exist

Series([], dtype: bool)

What is the Numpy object `nan` used for? (Write a descriptive answer.)

?
ANSWER: Marking a data point as invalid.

In [ ]:
#NaN = not a number, represents entries that are not defined
#vs null: represents "no value" or "nothing", not even empty str or zero
#NaN is usually result of mathematical operation that doesn't make sense

Write (and verify) a function that performs scalar division with built-in handling of the edge case (i.e. return a value instead of just trapping the error):

In [98]:
#ANSWER
#scalar = is a type that can have single value eg 5, 3.15, 'Bob'

def try_divide(x, y):
    try:
        return x/y
    except TypeError:
        return 'NaN'

print(try_divide('Bob', 4))
print(try_divide(0.1, 5))

NaN
0.02


Apply the Pandas `isna` function to the following data objects:

In [99]:
x = 2.3
y = np.nan
print(x, y)

2.3 nan


In [101]:
#ANSWER
print(pd.isna(x))
print(pd.isna(y))

False
True


In [102]:
array = np.array([[1, np.nan, 3], [4, 5, np.nan]])
print(array)

[[ 1. nan  3.]
 [ 4.  5. nan]]


In [106]:
#ANSWER
pd.isna(array)

array([[False,  True, False],
       [False, False,  True]])

How is the pandas I/O parameter `na_values` used?

? ANSWER: 

In [ ]:
#na_values = parameter used to tell pandas what to consider as NaN value (will print NaN in place of those values)
#eg: df = pd.read_csv('Example.csv', na_values = "Not Available")
#by-default pandas consider #N/A, -NaN, -n/a, N/A, NULL etc as NaN value
#https://www.geeksforgeeks.org/use-of-na_values-parameter-in-read_csv-function-of-pandas-in-python/

## Data Profiling

### Counts

When there are categorical variables in a dataset we will want to know how many possible values there are in each column. (Nb. If the dataset is a sample of a larger one, our sample may not capture all possible values of every categorical.)

How many (different) seasons are in `bikes`?

In [113]:
#ANSWER

seasons = bikes.season.unique()
print(seasons)

season_counts = bikes['season'].value_counts()
print(season_counts)

[1 2 3 4]
3    4496
2    4409
1    4242
4    4232
Name: season, dtype: int64


### Ranges

Print the range of the `instant`, `dteday`, and `windspeed` columns: 

In [186]:
#ANSWER
print("RANGES")
print("instant range :", bikes.instant.max() - bikes.instant.min())
print("dteday range :", pd.to_datetime(bikes["dteday"]).max() - pd.to_datetime(bikes["dteday"]).min())
print("windspeed range :", bikes.windspeed.max() - bikes.windspeed.min())


RANGES
instant range : 17378
dteday range : 730 days 00:00:00
windspeed range : 0.8507


Compute and print the overall minimum and maximum of the numeric data columns:

In [270]:
print("MINS and MAXS")
print("instant min :", bikes.instant.min(), "and instant max :", bikes.instant.max())
print("dteday min :", bikes.dteday.min(), "and dteday max :", bikes.dteday.max())
print("windspeed min :", bikes.windspeed.min(), "and windspeed max :", bikes.windspeed.max())

MINS and MAXS
instant min : 1 and instant max : 17379
dteday min : 2011-01-01 and dteday max : 2012-12-31
windspeed min : 0.0 and windspeed max : 0.8507


In [189]:
bikes.head(3)
# to get a glimpse at which columns contain numeric data (i.e. everything)

instant      dteday  season  yr  mnth  hr  holiday  weekday  workingday  \
0        1  2011-01-01       1   0     1   0        0        6           0   
1        2  2011-01-01       1   0     1   1        0        6           0   
2        3  2011-01-01       1   0     1   2        0        6           0   

   weathersit  temp   atemp   hum  windspeed  casual  registered  cnt  
0           1  0.24  0.2879  0.81        0.0       3          13   16  
1           1  0.22  0.2727  0.80        0.0       8          32   40  
2           1  0.22  0.2727  0.80        0.0       5          27   32

In [190]:
#provided: bikes_min, bikes_max = (min(bikes.min()), max(bikes.max()))
#provided: bikes_min, bikes_max

for col in bikes.columns:
    print(col, "min: ", bikes.col.min(), "and max: ", bikes.col.max())


AttributeError: 'DataFrame' object has no attribute 'col'

### Quantiles

Pandas makes computing quantiles easy. This is how to get the median of a Series:

In [130]:
bikes['atemp'].quantile(0.5)

0.4848

Of course, the `quantiles` method can take a tuple as its argument. Compute the 10th, 25th, 50th, 75th, and 90th percentiles in one line of code: 

In [129]:
#ANSWER
bikes['atemp'].quantile([0.1, 0.25, 0.5, 0.75, 0.9])

0.10    0.2424
0.25    0.3333
0.50    0.4848
0.75    0.6212
0.90    0.6970
Name: atemp, dtype: float64

### Cuts

Sometimes we want to split the sample not by the quantiles of the distribution but by the range of the data. Let's take a closer look at `atemp`:

In [131]:
type(bikes['atemp'])

pandas.core.series.Series

In [133]:
bikes.sample(5)
#df.sample() returns random sample of items where n=#items to return

instant      dteday  season  yr  mnth  hr  holiday  weekday  \
10182    10183  2012-03-05       1   1     3   8        0        1   
6242      6243  2011-09-22       3   0     9  16        0        4   
2276      2277  2011-04-09       2   0     4  17        0        6   
3959      3960  2011-06-18       2   0     6  21        0        6   
11318    11319  2012-04-21       2   1     4  19        0        6   

       workingday  weathersit  temp   atemp   hum  windspeed  casual  \
10182           1           1  0.20  0.2273  0.59     0.1045      13   
6242            1           2  0.68  0.6364  0.74     0.1343      39   
2276            0           2  0.38  0.3939  0.82     0.0896     128   
3959            0           2  0.72  0.6818  0.66     0.1045      58   
11318           0           3  0.56  0.5303  0.73     0.4925       9   

       registered  cnt  
10182         415  428  
6242          262  301  
2276          129  257  
3959          125  183  
11318          45   54

Suppose we decide to sort these values into 4 bins of equal width, but we want to apply the resulting groups to the entire DataFrame. Basically, we need to add a row label that indcates which bin each sample belongs in. Let's call this label "atemp_level", and use the `cut` method to populate it:

In [167]:
atemp_level = pd.cut(bikes['atemp'], bins = 4)         

What is `atemp_level`?

In [0]:
#ANSWER
#segments the data into 4 bins of equal value range (wrt atemp value range)

Here is a random sample of `atemp_level`:

In [191]:
atemp_level.sample(5)          

2375     (0.25, 0.5]
11276    (0.25, 0.5]
4472     (0.5, 0.75]
6503     (0.25, 0.5]
13586    (0.5, 0.75]
Name: atemp, dtype: category
Categories (4, interval[float64]): [(-0.001, 0.25] < (0.25, 0.5] < (0.5, 0.75] < (0.75, 1.0]]

So, by default, `cut` produces labels that indicate the bin boundaries for each element in the series it was applied to. Usually, we will specify labels that are appropriate to the discretisation we are applying:

In [199]:
atemp_level = pd.cut(bikes['atemp'], bins = 4, labels = ["cool", "mild", "warm", "hot"])
atemp_level.sample(5)          

#"cool" corresponds to (-0.001, 0.25]
#"mild" corresponds to (0.25, 0.5]
#and so on

1545     mild
1689     mild
6631     mild
16952    cool
13437    warm
Name: atemp, dtype: category
Categories (4, object): ['cool' < 'mild' < 'warm' < 'hot']

Incorporate the new `atemp_level` column into the `bikes` DataFrame and use it to count the number of "mild" `atemp` entries in `season` 2:

In [203]:
#ANSWER
bikes.insert(12, "atemp_level", atemp_level)

In [202]:
bikes.head(5)

instant      dteday  season  yr  mnth  hr  holiday  weekday  workingday  \
0        1  2011-01-01       1   0     1   0        0        6           0   
1        2  2011-01-01       1   0     1   1        0        6           0   
2        3  2011-01-01       1   0     1   2        0        6           0   
3        4  2011-01-01       1   0     1   3        0        6           0   
4        5  2011-01-01       1   0     1   4        0        6           0   

   weathersit  temp   atemp atemp_level   hum  windspeed  casual  registered  \
0           1  0.24  0.2879        mild  0.81        0.0       3          13   
1           1  0.22  0.2727        mild  0.80        0.0       8          32   
2           1  0.22  0.2727        mild  0.80        0.0       5          27   
3           1  0.24  0.2879        mild  0.75        0.0       3          10   
4           1  0.24  0.2879        mild  0.75        0.0       0           1   

   cnt  
0   16  
1   40  
2   32  
3   13  
4    1

In [212]:
#count the number of "mild" atemp_level entries in season = 2

#(bikes["atemp_level"] == "mild") & (bikes["season"] == 2)
#gives boolean series

#bikes[ (bikes["atemp_level"] == "mild") & (bikes["season"] == 2)]
#gives df

len(bikes[ (bikes["atemp_level"] == "mild") & (bikes["season"] == 2)])

1829

*Nb. The `atemp_level` variable we created is what the R language calls a "factor". Pandas has introduced a new data type called "category" that is similar to R's factors.*

# Synthetic Data

Sometimes we may want to generate test data, or we may need to initalise a series, matrix, or data frame for input to an algorithm. Numpy has several methods we can use for this.

Execute the following, then check the shape and content of each variable:

In [139]:
# Creating arrays with initial values
a = np.zeros((3))
b = np.ones((1,3))
c = np.random.randint(1,10,(2,3,4))   # randint(low, high, size)
d = np.arange(4)
e = np.array( [[1,2,3,4], [5,6,7,8]] )

In [148]:
print(a)
#shape of array = shape tuple = lengths of corresponding array dimensions
print(a.shape) #also can use np.shape(a)


print(b)
print(b.shape)


print(c)
print(c.shape)


print(d)
print(d.shape)


print(e)
print(e.shape)

[0. 0. 0.]
(3,)
[[1. 1. 1.]]
(1, 3)
[[[4 9 1 4]
  [8 5 1 9]
  [3 6 1 7]]

 [[2 3 7 6]
  [3 3 1 2]
  [4 3 9 6]]]
(2, 3, 4)
[0 1 2 3]
(4,)
[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [0]:
# Cleaning Data

## Load Data

Load rock.csv and clean the dataset.

In [151]:
import pandas as pd
df = pd.read_csv("rock.csv")
df.head()

Song Clean ARTIST CLEAN Release Year  \
0        Caught Up in You  .38 Special         1982   
1            Fantasy Girl  .38 Special          NaN   
2         Hold On Loosely  .38 Special         1981   
3  Rockin' Into the Night  .38 Special         1980   
4       Art For Arts Sake         10cc         1975   

                                COMBINED  First?  Year?  PlayCount  F*G  
0        Caught Up in You by .38 Special       1      1         82   82  
1            Fantasy Girl by .38 Special       1      0          3    0  
2         Hold On Loosely by .38 Special       1      1         85   85  
3  Rockin' Into the Night by .38 Special       1      1         18   18  
4              Art For Arts Sake by 10cc       1      1          1    1

## Check Column Names

Check column names and clean.

In [152]:
df.info()
# summary of a df, shows how many non-null values there are

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2230 entries, 0 to 2229
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   Song Clean    2230 non-null   object
 1   ARTIST CLEAN  2230 non-null   object
 2   Release Year  1653 non-null   object
 3   COMBINED      2230 non-null   object
 4   First?        2230 non-null   int64 
 5   Year?         2230 non-null   int64 
 6   PlayCount     2230 non-null   int64 
 7   F*G           2230 non-null   int64 
dtypes: int64(4), object(4)
memory usage: 139.5+ KB


## Replace Null Values With 0

Check 'release' column whether this column have any null value or not. Replace null value with 0.

In [153]:
df['Release Year']
# NaN values are null

0       1982
1        NaN
2       1981
3       1980
4       1975
        ... 
2225     NaN
2226    1981
2227    1975
2228    1983
2229    1973
Name: Release Year, Length: 2230, dtype: object

In [154]:
df['Release Year'] = df['Release Year'].fillna(0)
# takes all null values, replaces them with 0

df['Release Year']

0       1982
1          0
2       1981
3       1980
4       1975
        ... 
2225       0
2226    1981
2227    1975
2228    1983
2229    1973
Name: Release Year, Length: 2230, dtype: object

In [158]:
df['Release Year'] == 'SONGFACTS.COM'
#produces panda series, boolean (True only for row that corresponds to release yr = songfacts.com)

0       False
1       False
2       False
3       False
4       False
        ...  
2225    False
2226    False
2227    False
2228    False
2229    False
Name: Release Year, Length: 2230, dtype: bool

In [157]:
df[df['Release Year'] == 'SONGFACTS.COM']
#produces df with row that corresponds to release yr = songfacts.com

Song Clean    ARTIST CLEAN   Release Year  \
1504  Bullfrog Blues  Rory Gallagher  SONGFACTS.COM   

                              COMBINED  First?  Year?  PlayCount  F*G  
1504  Bullfrog Blues by Rory Gallagher       1      1          1    1

In [159]:
df[df['Release Year'] == '1071']

Song Clean ARTIST CLEAN Release Year             COMBINED  First?  Year?  \
547      Levon   Elton John         1071  Levon by Elton John       1      1   

     PlayCount  F*G  
547          8    8

In [160]:
#df.iloc[1,0] = 'something' 
    # where 1 is row number (index), 0 is column number (index)
    # = ____ changes the value for that cell index[1,0]

#df.head()

Song Clean ARTIST CLEAN Release Year  \
0        Caught Up in You  .38 Special         1982   
1               something  .38 Special            0   
2         Hold On Loosely  .38 Special         1981   
3  Rockin' Into the Night  .38 Special         1980   
4       Art For Arts Sake         10cc         1975   

                                COMBINED  First?  Year?  PlayCount  F*G  
0        Caught Up in You by .38 Special       1      1         82   82  
1            Fantasy Girl by .38 Special       1      0          3    0  
2         Hold On Loosely by .38 Special       1      1         85   85  
3  Rockin' Into the Night by .38 Special       1      1         18   18  
4              Art For Arts Sake by 10cc       1      1          1    1

## Check Datatypes of Dataset

Check datatypes of the dataset. Is there any column which should be int instead of object? Fix the column. 

In [161]:
datatypeseries = df.dtypes
print('data type of each column of dataframe :')
print(datatypeseries)

data type of each column of dataframe :
Song Clean      object
ARTIST CLEAN    object
Release Year    object
COMBINED        object
First?           int64
Year?            int64
PlayCount        int64
F*G              int64
dtype: object


In [219]:
df['Release Year'].value_counts()

0                577
1973             104
1977              83
1975              83
1970              81
1971              75
1969              72
1980              70
1978              64
1979              63
1967              61
1981              61
1983              60
1976              56
1982              54
1984              51
1972              50
1974              48
1968              46
1987              39
1985              39
1986              37
1991              34
1989              32
1966              30
1988              29
1965              28
1994              25
1990              22
1993              19
1992              14
1964              14
1999              13
1995              10
1963               9
1996               9
1997               9
2002               6
1998               6
2012               5
2004               5
2005               5
2001               4
2000               3
1962               3
2011               3
2003               3
2007         

In [229]:
#release year should be int not object
df['Release Year'] = df['Release Year'].replace(['SONGFACTS.COM'],'1970')
df['Release Year'].value_counts()

# Replace multiple values in a specific column
#df['column name'] = df['column name'].replace(['1st old value','2nd old value',...],'new value')

0       577
1973    104
1977     83
1975     83
1970     82
1971     75
1969     72
1980     70
1978     64
1979     63
1967     61
1981     61
1983     60
1976     56
1982     54
1984     51
1972     50
1974     48
1968     46
1987     39
1985     39
1986     37
1991     34
1989     32
1966     30
1988     29
1965     28
1994     25
1990     22
1993     19
1992     14
1964     14
1999     13
1995     10
1963      9
1996      9
1997      9
2002      6
1998      6
2012      5
2004      5
2005      5
2001      4
1962      3
2011      3
2003      3
2007      3
2008      3
2000      3
2014      2
2013      2
2006      1
1961      1
1958      1
1955      1
1071      1
Name: Release Year, dtype: int64

## Check Min, Max of Each Column

Is there any illogical value in any column? How can we fix that?

In [230]:
df.head(3)

Song Clean ARTIST CLEAN Release Year  \
0  Caught Up in You  .38 Special         1982   
1         something  .38 Special            0   
2   Hold On Loosely  .38 Special         1981   

                          COMBINED  First?  Year?  PlayCount  F*G  
0  Caught Up in You by .38 Special       1      1         82   82  
1      Fantasy Girl by .38 Special       1      0          3    0  
2   Hold On Loosely by .38 Special       1      1         85   85

In [267]:
df.info()
df[''].value_counts()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2230 entries, 0 to 2229
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Song Clean    2 non-null      float32
 1   Artist Clean  0 non-null      float32
 2   Release Year  2230 non-null   float32
 3   Combined      0 non-null      float32
 4   First?        2230 non-null   float32
 5   Year?         2230 non-null   float32
 6   PlayCount     2230 non-null   float32
 7   F*G           2230 non-null   float32
dtypes: float32(8)
memory usage: 69.8 KB


0.0       577
1973.0    104
1975.0     83
1977.0     83
1970.0     82
1971.0     75
1969.0     72
1980.0     70
1978.0     64
1979.0     63
1981.0     61
1967.0     61
1983.0     60
1976.0     56
1982.0     54
1984.0     51
1972.0     50
1974.0     48
1968.0     46
1985.0     39
1987.0     39
1986.0     37
1991.0     34
1989.0     32
1966.0     30
1988.0     29
1965.0     28
1994.0     25
1990.0     22
1993.0     19
1992.0     14
1964.0     14
1999.0     13
1995.0     10
1997.0      9
1963.0      9
1996.0      9
1998.0      6
2002.0      6
2005.0      5
2012.0      5
2004.0      5
2001.0      4
1962.0      3
2000.0      3
2007.0      3
2003.0      3
2011.0      3
2008.0      3
2013.0      2
2014.0      2
1961.0      1
2006.0      1
1958.0      1
1955.0      1
1071.0      1
Name: Release Year, dtype: int64

In [268]:
print("MINS")
print(df.min())


MINS
Song Clean      45.0
Artist Clean     NaN
Release Year     0.0
Combined         NaN
First?           1.0
Year?            0.0
PlayCount        0.0
F*G              0.0
dtype: float32


In [269]:
print("MAXS")
print(df.max())


MAXS
Song Clean      1979.0
Artist Clean       NaN
Release Year    2014.0
Combined           NaN
First?             1.0
Year?              1.0
PlayCount        142.0
F*G              142.0
dtype: float32


In [ ]:
#which are illogical values?
#based on release year values, eg of illogical value = 1071, can replace values 

## Write Some Functions

## Write a function that will take a row of a DataFrame and print out the song, artist, and whether or not the release date is < 1970

In [245]:
def bef_1970(row_index):
#where row index in this case between 0 to 2229
    
    if int(df.loc[row_index, 'Release Year']) < 1970:
        print("before 1970")
        print(df.loc[row_index, "Song Clean"])
        print(df.loc[row_index, "ARTIST CLEAN"])
        
    else:
        print("after 1970")
        print(df.loc[row_index, "Song Clean"])
        print(df.loc[row_index, "ARTIST CLEAN"])

In [246]:
bef_1970(2000)

after 1970
Seven Nation Army
The White Stripes


In [ ]:
#row = int(input("Enter a row number (from 0 to 2229): "))
#use this if you want to allow user input

In [249]:
#How to change column names
df.rename(columns={'ARTIST CLEAN':'Artist Clean'}, inplace=True)
df.rename(columns={'COMBINED': 'Combined'}, inplace=True)
df.head(4)

Song Clean Artist Clean Release Year  \
0        Caught Up in You  .38 Special         1982   
1               something  .38 Special            0   
2         Hold On Loosely  .38 Special         1981   
3  Rockin' Into the Night  .38 Special         1980   

                                Combined  First?  Year?  PlayCount  F*G  
0        Caught Up in You by .38 Special       1      1         82   82  
1            Fantasy Girl by .38 Special       1      0          3    0  
2         Hold On Loosely by .38 Special       1      1         85   85  
3  Rockin' Into the Night by .38 Special       1      1         18   18

## Write a function that converts cells in a DataFrame to float and otherwise replaces them with np.nan

In [169]:
def convert_to_float(column):
    column = pd.to_numeric(column, errors='coerce')
    return column

#arg must be a list, tuple, 1-d array, or Series
#that's why we can apply (function) to column but not to entire df 

In [253]:
convert_to_float('Release Year')

nan

In [254]:
convert_to_float(df['Release Year'])

0       1982
1          0
2       1981
3       1980
4       1975
        ... 
2225       0
2226    1981
2227    1975
2228    1983
2229    1973
Name: Release Year, Length: 2230, dtype: int64

## Apply these functions to your dataset

In [171]:
df.apply(convert_to_float)

Song Clean  ARTIST CLEAN  Release Year  COMBINED  First?  Year?  \
0            NaN           NaN        1982.0       NaN       1      1   
1            NaN           NaN           0.0       NaN       1      0   
2            NaN           NaN        1981.0       NaN       1      1   
3            NaN           NaN        1980.0       NaN       1      1   
4            NaN           NaN        1975.0       NaN       1      1   
...          ...           ...           ...       ...     ...    ...   
2225         NaN           NaN           0.0       NaN       1      0   
2226         NaN           NaN        1981.0       NaN       1      1   
2227         NaN           NaN        1975.0       NaN       1      1   
2228         NaN           NaN        1983.0       NaN       1      1   
2229         NaN           NaN        1973.0       NaN       1      1   

      PlayCount  F*G  
0            82   82  
1             3    0  
2            85   85  
3            18   18  
4             1    1  
...         ...  ...  
2225          1    0  
2226         32   32  
2227        109  109  
2228          1    1  
2229          2    2  

[2230 rows x 8 columns]

In [263]:
#write above as compressed function (so that function can take df and not just columns)
def float_converter(dataframe): 
    dataframe = dataframe.apply(pd.to_numeric, errors='coerce', downcast='float')
    return dataframe

new_df = float_converter(df)
new_df

Song Clean  Artist Clean  Release Year  Combined  First?  Year?  \
0            NaN           NaN        1982.0       NaN     1.0    1.0   
1            NaN           NaN           0.0       NaN     1.0    0.0   
2            NaN           NaN        1981.0       NaN     1.0    1.0   
3            NaN           NaN        1980.0       NaN     1.0    1.0   
4            NaN           NaN        1975.0       NaN     1.0    1.0   
...          ...           ...           ...       ...     ...    ...   
2225         NaN           NaN           0.0       NaN     1.0    0.0   
2226         NaN           NaN        1981.0       NaN     1.0    1.0   
2227         NaN           NaN        1975.0       NaN     1.0    1.0   
2228         NaN           NaN        1983.0       NaN     1.0    1.0   
2229         NaN           NaN        1973.0       NaN     1.0    1.0   

      PlayCount    F*G  
0          82.0   82.0  
1           3.0    0.0  
2          85.0   85.0  
3          18.0   18.0  
4           1.0    1.0  
...         ...    ...  
2225        1.0    0.0  
2226       32.0   32.0  
2227      109.0  109.0  
2228        1.0    1.0  
2229        2.0    2.0  

[2230 rows x 8 columns]

## Describe the new float-only DataFrame.

In [264]:
new_df.describe

<bound method NDFrame.describe of       Song Clean  Artist Clean  Release Year  Combined  First?  Year?  \
0            NaN           NaN        1982.0       NaN     1.0    1.0   
1            NaN           NaN           0.0       NaN     1.0    0.0   
2            NaN           NaN        1981.0       NaN     1.0    1.0   
3            NaN           NaN        1980.0       NaN     1.0    1.0   
4            NaN           NaN        1975.0       NaN     1.0    1.0   
...          ...           ...           ...       ...     ...    ...   
2225         NaN           NaN           0.0       NaN     1.0    0.0   
2226         NaN           NaN        1981.0       NaN     1.0    1.0   
2227         NaN           NaN        1975.0       NaN     1.0    1.0   
2228         NaN           NaN        1983.0       NaN     1.0    1.0   
2229         NaN           NaN        1973.0       NaN     1.0    1.0   

      PlayCount    F*G  
0          82.0   82.0  
1           3.0    0.0  
2          85.

>




---



---



> > > > > > > > > © 2021 Institute of Data


---



---



