<div>
<img src=https://www.institutedata.com/wp-content/uploads/2019/10/iod_h_tp_primary_c.svg width="300">
</div>

1. Compute the scaler product of two vectors

> In mathematics, the dot product or scalar product is an algebraic operation that takes two equal-length sequences of numbers (usually coordinate vectors) and returns a single number. 

> we can calculate it this way:

        a · b = ax × bx + ay × by
        
Hint: [Dot Product](https://www.mathsisfun.com/algebra/vectors-dot-product.html)

In [28]:
import numpy as np

In [29]:
a = [-12, 16]
b = [12, 9]

In [30]:
#test
print(a[0])

-12


In [31]:
#answer1
a_dot_b = (a[0]*b[0]) + (a[1]*b[1])
print(a_dot_b)

0


In [32]:
print(list(zip(a,b)))

[(-12, 12), (16, 9)]


In [33]:
#answer2
def dot_pdt_of(vector1, vector2):
#where vector1 and vector2 are LISTS

    return sum(
        element1n*element2n
        for element1n, element2n in zip(vector1,vector2)
    )


dot_pdt_of(a,b)

0

2. Compute the cross product of two vectors

> When a and b start at the origin point (0,0,0), the Cross Product will end at:

        cx = aybz − azby
        cy = azbx − axbz
        cz = axby − aybx
        
Hint: [Cross Product](https://www.mathsisfun.com/algebra/vectors-cross-product.html)

In [34]:
x = np.array([[1,2,3], [4,5,6]])
y = np.array([[4,5,6], [1,2,3]])

In [35]:
#test
print(x[0,1])

2


In [36]:
cross_x_cx = (x[0,1]*x[1,2]) - (x[0,2]*x[1,1])
cross_x_cy = (x[0,2]*x[1,0]) - (x[0,0]*x[1,2])
cross_x_cz = (x[0,0]*x[1,1]) - (x[0,1]*x[1,0])
cross_x = np.array([[cross_x_cx, cross_x_cy, cross_x_cz]])
print("cross pdt of x is :", cross_x)

cross_y_cx = (y[0,1]*y[1,2]) - (y[0,2]*y[1,1])
cross_y_cy = (y[0,2]*y[1,0]) - (y[0,0]*y[1,2])
cross_y_cz = (y[0,0]*y[1,1]) - (y[0,1]*y[1,0])
cross_y = np.array([[cross_y_cx, cross_y_cy, cross_y_cz]])
print("cross pdt of y is :", cross_y)

cross pdt of x is : [[-3  6 -3]]
cross pdt of y is : [[ 3 -6  3]]


In [37]:
def cross_pdt_of(arr):
#where x is nparray of 2 vectors
    cross_pdt_x = (arr[0,1]*arr[1,2]) - (arr[0,2]*arr[1,1])
    cross_pdt_y = (arr[0,2]*arr[1,0]) - (arr[0,0]*arr[1,2])
    cross_pdt_z = (arr[0,0]*arr[1,1]) - (arr[0,1]*arr[1,0])
    print("cross pdt of ", arr, " is : ", np.array([[cross_pdt_x, cross_pdt_y, cross_pdt_z]]))
  
#if given indiv vectors as lists instead of combined nparray?
sample_vector1_as_list = [2,8,1]
sample_vector2_as_list = [3,4,7]
sample_arr = np.array([sample_vector1_as_list, sample_vector2_as_list])
cross_pdt_of(sample_arr)

print(cross_pdt_of(x))

cross pdt of  [[2 8 1]
 [3 4 7]]  is :  [[ 52 -11 -16]]
cross pdt of  [[1 2 3]
 [4 5 6]]  is :  [[-3  6 -3]]
None


3. Compute the Hademard product (entry-wise multiplication) of two vectors.

> In mathematics, the Hadamard product (also known as the Schur product[1] or the entrywise product[2]:ch. 5) is a binary operation that takes two matrices of the same dimensions and produces another matrix of the same dimension as the operands where each element i, j is the product of elements i, j of the original two matrices. It should not be confused with the more common matrix product. It is attributed to, and named after, either French mathematician Jacques Hadamard or German mathematician Issai Schur. [Wiki](https://en.wikipedia.org/wiki/Hadamard_product_(matrices))

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/4eb9bb54b2820fb3583901ec05bc4b474b6d90bc)

In [39]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [48]:
#answer1
hadamard_ab_00 = a[0,0]*b[0,0]
hadamard_ab_01 = a[0,1]*b[0,1]
hadamard_ab_10 = a[1,0]*b[1,0]
hadamard_ab_11 = a[1,1]*b[1,1]

hadamard_ab = np.array([[hadamard_ab_00, hadamard_ab_01], [hadamard_ab_10, hadamard_ab_11]])
print(hadamard_ab)

[[ 5 12]
 [21 32]]


In [56]:
#answer2
def hadamard_pdt_of(matrix1, matrix2):
#where matrix1 and matrix2 are nparrays

    for m1, m2 in matrix1, matrix2:
        
        list_output = np.multiply(matrix1,matrix2, dtype=list)
        #np.multiply used to compute multiplication of 2 arrays
        #returns pdt of arr1 and arr2, element-wise
        
        return(np.array(list_output))

hadamard_pdt_of(a,b)

array([[5, 12],
       [21, 32]], dtype=object)

4. Compute the sum of two matrices.
(https://wikimedia.org/api/rest_v1/media/math/render/svg/0fb7845af355c550d44020e52699069c044126a9)

In [72]:
# Program to add two matrices using nested loop

X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]

Y = [[5,8,1],
    [6,7,3],
    [4,5,9]]

#result = [[0,0,0], [0,0,0], [0,0,0]]

In [76]:
#test
Xarr, Yarr = np.array(X), np.array(Y)
result = np.add(Xarr, Yarr)
print(result)

[[17 15  4]
 [10 12  9]
 [11 13 18]]


In [115]:
#test

C = [1,2,3]
D = [2,2,2]

result = [] #initiate empty list

for column_c, column_d in zip(C,D):
    result.append(column_c + column_d)
#zip function creates zip object: iterator of tuples
#each tuple: first item of each passed iterator is paired tgt


print(result) #should be [3,4,5]

[3, 4, 5]


In [121]:
#answer - using nested loop (loop within loop)

#for every row, iterate through every column (element) to create list
#result = list of lists

new_matrix = []
for row_x, row_y in zip(X, Y):
    
    new_row = [] #initiate empty list
    for column_x, column_y in zip(row_x, row_y):
        
        new_row.append(column_x + column_y)
    
    new_matrix.append(new_row)

print(new_matrix)


[[17, 15, 4], [10, 12, 9], [11, 13, 18]]


5. Compute the product of two matrices.

![](https://upload.wikimedia.org/wikipedia/commons/e/eb/Matrix_multiplication_diagram_2.svg)

In [122]:
# Program to multiply two matrices using nested loops

# 3x3 matrix
X = [[12,7,3],
    [4,5,6],
    [7,8,9]]

# 3x4 matrix
Y = [[5,8,1,2],
    [6,7,3,0],
    [4,5,9,1]]

# result is 3x4
#result = [[0,0,0,0], [0,0,0,0], [0,0,0,0]]

In [123]:
#test
Xarr = np.array(X)
Yarr = np.array(Y)
np.matmul(Xarr, Yarr)

array([[114, 160,  60,  27],
       [ 74,  97,  73,  14],
       [119, 157, 112,  23]])

In [136]:
#answer - using nested loop (loop within loop)

#for every row of X, iterate through every row (of one column) of Y to create list
#result = list of lists

#steps
#1: (all elements in) ONE row of X
#2: multiplied against (all elements in) ALL columns of Y
#3: zoom in >>> for ONE column of Y >>> each row_x element * column_y element

#need to use "range" because involves indexing

new_matrix = [] #initiate empty list
for a in range(len(X)): #every "a" in X refers to one element in list X i.e. one "row"

    new_row = [] 
    for b in range(len(Y[0])): #len(Y[0]) = no. of columns /// vs /// len(Y) = no. of rows
        
        accummulated_sum = 0
        for c in range(len(Y)):
            component = (X[a][c] * Y[c][b])
            accummulated_sum = accummulated_sum + component
            
        new_row.append(accummulated_sum)
    
    new_matrix.append(new_row)

print(new_matrix)


[[114, 160, 60, 27], [74, 97, 73, 14], [119, 157, 112, 23]]


6. Compute the determinant of an n x n matrix.

![](https://integratedmlai.com/wp-content/uploads/2018/12/Matrix_Det_2x2.png)

Hint: [Find the Determinant of a Matrix with Pure Python without Numpy or Scipy](https://integratedmlai.com/find-the-determinant-of-a-matrix-with-pure-python-without-numpy-or-scipy/)

Hint: Use 
> np.linalg.det

In [137]:
matrix = [[-2,2,-3],
          [-1,1,3],
          [2,0,-1]]

In [139]:
#compute for nxn matrix not 3x3
#using np.linalg.det which computes determinant of array
det = np.linalg.det(matrix) #where matrix can be any nxn matrix
print(det)

17.999999999999996


7. Compute the inverse of an n x n matrix.

For a 3×3 matrix

![](http://mathworld.wolfram.com/images/equations/MatrixInverse/NumberedEquation3.gif)

the matrix inverse is

![](http://mathworld.wolfram.com/images/equations/MatrixInverse/NumberedEquation4.gif)

Hint: Use 
> from numpy.linalg import inv

In [140]:
a = np.array([[1., 2.], [3., 4.]])

In [143]:
from numpy.linalg import inv
#linalg.inv() computes multiplicative inverse of square matrix
#matrix needs to satisfy: dot(a, ainv) = dot(ainv, a) = eye(a.shape[0])
    #dot(a, ainv) = dot(ainv,a) --> it's a square matrix
    #.shape attribute --> returns no. of rows and columns as tuple
    #.shape[0] --> accesses no. of rows out of that tuple ^
    #np.eye --> pass a number n into this, get identity matrix with n rows and n columns

inv_a = np.linalg.inv(a)
print(inv_a)

[[-2.   1. ]
 [ 1.5 -0.5]]




---



---



> > > > > > > > > © 2021 Institute of Data


---



---



